on:
  pull_request:
  push:
    branches: ["master"]
    tags: [ 'v*.*.*' ]
name: Rust Build

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Dump Event Name
        run: echo "EVENT_NAME=$EVENT_NAME" >> $GITHUB_OUTPUT
        env: 
          EVENT_NAME: ${{ github.event_name }}

      - name: Build Rust Artifacts (PR)
        uses: bluebastion/dev-bb-rust-action@master
        with:
          fmt: true
          check: true
          clippy: true
          read_artifacts_pat: ${{ secrets.READ_ARTIFACTS_PAT }}
          ssh_key: ${{ secrets.RUNNER_10_2_4_50_SSH }}

      - name: Initiate Repo Dispatch
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.READ_ARTIFACTS_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d "{ \"event_type\": \"trigger-build\", \"client_payload\": { \"run_id\": \"${{ github.run_id }}\", \"repository\": \"${{ github.repository }}\", \"ref\":\"${{ github.ref_name }}\"}}"
